MyFirstWebsite/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyFirstWebsite.Models;
using MyFirstWebsite.Services;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MyFirstWebsite.Controllers
{
    public class ContactController : Controller
    {
        private IEmailService emailService;

        public ContactController(IEmailService emailService)
        {
            this.emailService = emailService;
        }
        // GET: /<controller>/
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(Contact contact)
        {
            if (ModelState.IsValid)
            {
                Task.Run(() => 
                {
                    var message = "Hello " + contact.Name + ",\n\n" + "I have received your message. I will respond shortly. \n\nBest regards,\n\nScott Mello";

                    emailService.SendEmail("scott.mello24@gmail.com", "From: " + contact.Name, "From: " + contact.Name + "\nEmail: " + contact.Email + "\n\n" + contact.Message);
                    emailService.SendEmail(contact.Email, "Message Confirmation", message);
                });

                return View("MessageComplete", contact);
            }

            return View(contact);
            
        }
    }
}

MyFirstWebsite/Controllers/FantasyController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using MyFirstWebsite.Models;
using MyFirstWebsite.Services;
using MyFirstWebsite.Services.Fantasy;
using MyFirstWebsite.ViewModels;
using System.Linq;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MyFirstWebsite.Controllers
{
    public class FantasyController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly IFantasyProsDataGrabber _fantasyProsDataGrabber;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IDraftService _draftService;
        private readonly IPlayerService _playerService;
        private readonly ITeamService _teamService;

        public FantasyController(IConfiguration configuration
                                , IFantasyProsDataGrabber fantasyProsDataGrabber
                                , AppDbContext appDbContext
                                , UserManager<ApplicationUser> userManager
                                , IDraftService draftService
                                , IPlayerService playerService
                                , ITeamService teamService)
        {
            _configuration = configuration;
            _fantasyProsDataGrabber = fantasyProsDataGrabber;
            _userManager = userManager;
            _draftService = draftService;
            _playerService = playerService;
            _teamService = teamService;
        }

        // GET: /<controller>/
        [HttpGet]
        public IActionResult Index()
        {
            FantasyViewModel fantasyViewModel = new FantasyViewModel();

            fantasyViewModel.Players = _fantasyProsDataGrabber.GetPlayers(ScoringType.Standard);
            fantasyViewModel.PageHeading = "Standard";

            return View(fantasyViewModel);
        }

        [HttpPost]
        public IActionResult Index(FantasyViewModel model)
        {
            model.Players = _fantasyProsDataGrabber.GetPlayers(model.ScoringType);
            model.PageHeading = _draftService.GetPageHeading(model.ScoringType);

            return View(model);
        }

        [Authorize]
        [HttpGet]
        public IActionResult New()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public IActionResult New(NewViewModel newDraft)
        {
            string userId = _userManager.GetUserId(User);

            Draft draft = _draftService.SetupDraft(newDraft, userId);

            _draftService.InsertDraft(draft);

            _draftService.Save();

            return RedirectToAction(nameof(Draft), new { id = draft.Id});
        }

        [Authorize]
        public IActionResult Draft(int id)
        {
            DraftViewModel draftViewModel = new DraftViewModel();
            var userId = _userManager.GetUserId(User);

            Draft draft = _draftService.GetDraft(id);
            Team userTeam = _teamService.GetUserTeam(draft);
            Team availablePlayers = _teamService.GetAvailablePlayers(draft);

            draftViewModel.LeagueName = draft.LeagueName;
            draftViewModel.TeamName = userTeam.TeamName;
            draftViewModel.DraftPosition = draft.UserDraftPosition;
            draftViewModel.NumberOfTeams = draft.NumberOfTeams;
            draftViewModel.MyPlayers = userTeam.Players.ToHashSet();
            draftViewModel.AvailablePlayers = availablePlayers.Players.ToHashSet();

            int pick = _draftService.GetPick(draft);
            draftViewModel.pick = pick;
            draftViewModel.round = _draftService.GetRound(pick, draft.NumberOfTeams);

            return View(draftViewModel);
        }

        [Authorize]
        public IActionResult Drafts() //user draft teams
        {   
            return View(_draftService.GetAllDrafts(_userManager.GetUserId(User)));
        }
    }//class
} //namespace

MyFirstWebsite/Views/Shared/_AddPlayerForm.cshtml
<form class="form-container" id="addPlayerForm">
    <h1>Add Player</h1>

    <div class="form-group">
        <label for="name"><b>Name</b></label>
        <input class="form-control"type="text" placeholder="Enter Player Name" name="name" id="addPlayerNameInput" required>
    </div>

    <div class="form-group">
        <label for="position"><b>Position</b></label>
        <select class="form-select" id="addPlayerPosition">
            <option value="0">QB</option>
            <option value="1">RB</option>
            <option value="2">WR</option>
            <option value="3">TE</option>
            <option value="4">DST</option>
            <option value="5">K</option>
        </select>
    </div>

    <button type="submit" class="btn btn-primary" id="submitPlayerButton">Submit</button>
    <button type="button" class="btn btn-danger" id="closeFormButton">Close</button>
</form>

MyFirstWebsite/Views/Shared/_Card.cshtml
@model DraftboardViewModel


@for (int i = 0, row = 0; i < Model.Players.Count; i += Model.NumberOfTeams, row++)
{
    var k = i + Model.NumberOfTeams - 1;
<div class="row col-md-12">
    @for (int j = i; j < i + Model.NumberOfTeams && j < Model.Players.Count; j++, k--)
    {
        @if (row % 2 == 1)
        {
            @if (k >= Model.Players.Count)
            {
                k = Model.Players.Count - 1;
            }
            @if (Model.Players.ElementAt(k).PositionDrafted == Model.Players.Count)
            {
                <div class="card col ml-auto">
                    <div class="card-body">
                        <h6 class="card-title">@Model.Players.ElementAt(k).Name</h6>
                        <footer>
                            <small class="text-muted bottom-right">
                                @Model.Players.ElementAt(k).Position
                            </small>
                        </footer>
                    </div>
                </div>
            }
            else
            {
                <div class="card col">
                    <div class="card-body">
                        <h6 class="card-title">@Model.Players.ElementAt(k).Name</h6>
                        <footer>
                            <small class="text-muted bottom-right">
                                @Model.Players.ElementAt(k).Position
                            </small>
                        </footer>
                    </div>
                </div>

            }
        }
        else
        {
            <div class="card col">
                <div class="card-body">
                    <h6 class="card-title">@Model.Players.ElementAt(j).Name</h6>
                    <footer>
                        <small class="text-muted bottom-right">
                            @Model.Players.ElementAt(j).Position
                        </small>
                    </footer>
                </div>
            </div>
        }
    }
</div>
}

MyFirstWebsite/Views/Shared/_Favicons.cshtml
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">

MyFirstWebsite/Views/Shared/_FlexCard.cshtml
@model DraftboardViewModel

@{int numPlayersLastRow = (Model.Players.Count % Model.NumberOfTeams > 0) ? Model.Players.Count % Model.NumberOfTeams : Model.NumberOfTeams; }
@{int numberofRows = (int)Math.Ceiling((double)Model.Players.Count / Model.NumberOfTeams); }
@for (int i = 0; i < numberofRows; i++)
{
    @if (i % 2 == 0)
    {
        <div class="d-flex flex-row">
            @for (int y = 1; y <= (i == numberofRows-1 ? numPlayersLastRow : Model.NumberOfTeams); y++)
            {
                <div class="card col ml-auto flex-item">
                    <div class="card-body">
                        <h6 class="card-title">@Model.Players.ElementAt((y + Model.NumberOfTeams * i)-1).Name</h6>
                        <footer>
                            <small class="text-muted bottom-right">
                                @Model.Players.ElementAt(y + (Model.NumberOfTeams * i) - 1).Position
                            </small>
                        </footer>
                    </div>
                </div>
            }
        </div>
    }
    else
    {
        <div class="d-flex flex-row-reverse">
            @for (int y = 1; y <= (i == numberofRows-1 ? numPlayersLastRow : Model.NumberOfTeams); y++)
            {
                <div class="card col ml-auto flex-item">
                    <div class="card-body">
                        <h6 class="card-title">@Model.Players.ElementAt((y + Model.NumberOfTeams * i) - 1).Name</h6>
                        <footer>
                            <small class="text-muted bottom-right">
                                @Model.Players.ElementAt(y + (Model.NumberOfTeams * i) - 1).Position
                            </small>
                        </footer>
                    </div>
                </div>
            }
        </div>
    }
}

MyFirstWebsite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/node_modules/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="~/content/site.css" rel="stylesheet" />
    @await Html.PartialAsync("_Favicons")
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" asp-controller="Home" asp-action="Index">
            <img src="~/images/my_logo.png" width="40" height="40" />
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav nav">
                <li class="nav-item" is-active-route asp-controller="Home" asp-action="Index">
                    <a class="nav-link" asp-controller="Home" asp-action="Index">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item" is-active-route asp-controller="Home" asp-action="About">
                    <a asp-controller="Home" asp-action="About" class="nav-link">About</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Links
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="https://github.com/Mello244688" target="_blank">GitHub</a>
                        <a class="dropdown-item" href="https://www.linkedin.com/in/scott-mello" target="_blank">LinkedIn</a>
                    </div>
                </li>
                <li class="nav-item" is-active-route asp-action="Index" asp-controller="Contact">
                    <a asp-controller="Contact" asp-action="Index" class="nav-link">Contact Me</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown2" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Fantasy Football
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown2">
                        <a class="dropdown-item" is-active-route asp-controller="Fantasy" asp-action="Index">ADP</a>
                        <a class="dropdown-item" is-active-route asp-controller="Fantasy" asp-action="New">New Draft</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" is-active-route asp-controller="Fantasy" asp-action="Drafts">My Drafts</a>
                    </div>
                </li>
            </ul>
            <partial name="_LoginPartial" />
        </div>
    </nav>

    <div class="container body-content col-md-12">
        <partial name="_CookieConsentPartial" />
        <div class="row justify-content-center" id="body-row">
            @RenderBody()
        </div>
        <hr />
        <footer>
            <p>&copy; 2018 - MyProject</p>
        </footer>
    </div>
    <script src="~/node_modules/jquery/dist/jquery.slim.min.js"></script>
    <script src="~/node_modules/jquery/dist/jquery.js"></script>
    <script src="~/node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/content/site.js"></script>
    @RenderSection("scripts", required: false)

</body>
</html>